version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y git
  pre_build:
    commands:
      - echo Nothing to do in the pre-build phase...
  build:
    commands:
      - echo Build started on `date`
      - git --version
  post_build:
    commands:
      - echo Post build here    
